name: Build and Publish to npm

on:
  push:
    branches:
      - main
    paths:
      - "projects/qsys-lib/**" # Only trigger when the library code changes

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build qsys-lib

      - name: Run tests
        run: npm run test qsys-lib --if-present

      - name: Check version changes
        id: check
        run: |
          PUBLISHED_VERSION=$(npm view qsys-lib version 2>/dev/null || echo "0.0.0")
          CURRENT_VERSION=$(node -p "require('./projects/qsys-lib/package.json').version")
          if [ "$PUBLISHED_VERSION" != "$CURRENT_VERSION" ]; then
            echo "version_changed=true" >> $GITHUB_OUTPUT
          else
            echo "version_changed=false" >> $GITHUB_OUTPUT
            echo "No version change detected. Current: $CURRENT_VERSION, Published: $PUBLISHED_VERSION"
          fi

      - name: Publish to npm
        if: steps.check.outputs.version_changed == 'true'
        run: cd dist/qsys-lib && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
